name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          version: v1.25.1 # renovate: datasource=github-tags depName=goreleaser/goreleaser
          args: build --single-target --snapshot --clean --output ./version
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.draft_release.outputs.tag_name }}
      - name: Version test
        id: version
        run: echo "output=$(./version bump 0.1.0)" >> "$GITHUB_OUTPUT"
      - name: Failed
        if: ${{ steps.version.outputs.output != '0.1.1' }}
        run: |-
          exit 1
      - name: Success
        if: ${{ steps.version.outputs.output == '0.1.1' }}
        run: |-
          exit 0

  docker-build:
    name: docker build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0
      - name: Build Docker image
        run: VERSION=$(git rev-parse --short HEAD) make docker-build docker-build-x-platform
      - name: Version test
        id: version
        run: |-
          echo "output=$(docker run ghcr.io/version-cli/version:latest bump 0.1.0)" >> "$GITHUB_OUTPUT"
      - name: Failed
        if: ${{ steps.version.outputs.output != '0.1.1' }}
        run: |-
          exit 1
      - name: Success
        if: ${{ steps.version.outputs.output == '0.1.1' }}
        run: |-
          exit 0
