name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          ref: ${{ github.head_ref }} # so PRs resolve to correct branch
          fetch-depth: 0 # needed for only_changed below
          persist-credentials: false
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ secrets.VERSION_CLI_UPDATER_APP_ID }}
          private-key: ${{ secrets.VERSION_CLI_UPDATER_PRIVATE_KEY }}
      - name: Prettify code
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          commit_message: "Prettier"
          only_changed: True
          github_token: ${{ steps.app-token.outputs.token }}
          prettier_options: --write . # the `.` targets all files which prettier _can_ parse, and ignores all others
